### ISSUE TITLE
Still in use?

### ISSUE THREAD

**Issue by icemac** [zopefoundation/z3c.breadcrumb#5]
Is this package still actively used or can it be archived?

Cc-ing contributors:

@mgedmin @agroszer @projekt01

P.S.: I personally do not use it.

**Comment by mgedmin** [comment]
I do not currently use it (although I had plans, many years ago).

I feel a strange fondness for this package and wouldn't mind helping with its maintenance.

**Comment by agroszer** [comment]
not in use here

**Comment by icemac** [comment]
I'll add a `maintained` topic to this repos to prevent it from being archived.
Thank you for your responses.
